name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run : bun install
    - run : bun run prepare
    - name: Publish to npm
      run : |
        bun run version.ts
        bun publish --ignore-scripts --access=public
      env :
        NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
        NPM_CONFIG_PROVENANCE: true
    - name: Publish to JSR
      run: bunx jsr publish --allow-dirty